### ISSUE TITLE
Longer duration

### ISSUE THREAD

**Issue by BobRay** [codrops/ProgressButtonStyles#2]
I've tried everything I can think of but I can't seem to make the progress bar last more than 4 or 5 seconds.

**Comment by razuro** [comment]
Increase the value here (default is 200) to prolong the loading time effect:
https://github.com/codrops/ProgressButtonStyles/blob/633fa0af9682123edbeee83aeef07f42e831bd76/index.html#L136

**Comment by BobRay** [comment]
Thanks.
